{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rintrojs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rintrojs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rintrojs/rintrojs_{{ version }}.tar.gz
  sha256: 50cb2a1bb15ec987044d30f441e35f0bdd327ae7ab46bb12e341671804c197a6

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-jsonlite
    - r-shiny
  run:
    - r-base
    - r-jsonlite
    - r-shiny

test:
  commands:
    - $R -e "library('rintrojs')"           # [not win]
    - "\"%R%\" -e \"library('rintrojs')\""  # [win]

about:
  home: https://github.com/carlganz/rintrojs
  license: AGPL-3.0-only
  summary: "A wrapper for the 'Intro.js' library (For more info: <http://www.introjs.com>).  This package makes it easy to include step-by-step introductions, and clickable hints in a 'Shiny'  application. It supports both static introductions in the UI, and programmatic introductions from  the server-side. "
  license_family: AGPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: rintrojs
# Type: Package
# Title: Wrapper for the 'Intro.js' Library
# Version: 0.2.2
# Authors@R: c( person("Carl", "Ganz", email = "carlganz@gmail.com", role = c("aut", "cre")), person("Afshin", "Mehrabani", role = c("ctb","cph"), comment = "intro.js in javascript/introjs") )
# Description: A wrapper for the 'Intro.js' library (For more info: <http://www.introjs.com>).  This package makes it easy to include step-by-step introductions, and clickable hints in a 'Shiny'  application. It supports both static introductions in the UI, and programmatic introductions from  the server-side.
# License: AGPL-3
# LazyData: TRUE
# Imports: shiny, jsonlite
# Depends: R (>= 3.0.0)
# RoxygenNote: 6.1.1
# URL: https://github.com/carlganz/rintrojs
# BugReports: https://github.com/carlganz/rintrojs/issues
# Suggests: testthat, covr
# NeedsCompilation: no
# Packaged: 2019-05-29 21:06:20 UTC; carlganz
# Author: Carl Ganz [aut, cre], Afshin Mehrabani [ctb, cph] (intro.js in javascript/introjs)
# Maintainer: Carl Ganz <carlganz@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-05-29 21:30:04 UTC
