travis:
  secure:
    BINSTAR_TOKEN: V6yr/dHXou9hx12i3sYrqp3I9nKFkh6jz7ufqpCmYapRDPOvb8VXsZo+SafKmfSOQElzytxQd2v0/ayp9iwtILWJ0VpJAY7OmmuCfbC2vF7Hcxw2lJ5UK+TSoZX/BE7iawHEv4Y7+ju1VkAHlmi3jNojFLY5jMQW13qoxCNu7WQYOBXyH0Zey/PIebvlzQb+iwKl76QWl9mWimAv+el5BYEgdLpziQMxAHiHDeMaW2Udl2ClJZbL4XtErJa+/nGeFfSlV+S3F7nGTVw9AVu3vUolcbL1dZ26925mPtcvFP5r34uHg4NqWaeGpjWVb3ZBNSjfesqgfQhE0ql8lUtr06w4vqXr1xKw08P0kCZIoZi2MWum6wL6u29Z2xPeE2lN7FXUY/p36eJYdL4kQV2M1ZRwY8QCb9h87uxtRp0ZF+fZlM7L27mLt6darZOFYrT6E4xp1xAeaBsebtYsGrjJ8kBr6LZVd/ldhbTJ6PwDMsafDmZqXwJ+NboEBcu1mk3J5Um4yDfhmWzO6Gl0Btc8c3Vmm1VxSFZbKczQ9V4gmBlm6+obrH4gKzx0wZNfy/Wj1DAcufM/doxzYsYNFOKd22+UST5c9uZJoDRgC/yc/IDeZPrh1YOtZPApqyJbdb1wZUX6UXCWGzjFHek0gBJA7FwnkFbphikjOJc7qrR5rvo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
