appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: f92bYFEcwwMOX0EEcib7CAFzUhqnxjSEFAgSsdk6gxyfidjWevdrub1LiijUtXkMEZqPriYSVT+A6OVfgkX5HsxHRyZl+Pmpc3X0dYFWl62r36FzadJ2epI5wHxYdhWuILHxzPHF8PBACMZUff7/9ukYKSdPyKM/nhoagefM4s7wlMd7jUDblaCbOwj/uaIgtUnB9OmACqapSBSQfEgKYQdBedPimWTqIbod6v8KNhYGNM/6b1pBLsp/vV8W8QZ5bV9ypJl6coIRPg0etjjJIqdGPKdrBq4S1UI6JxZ1VpQoWNnF9kUMmfwEHDMa1vdK8VsgTvXu8rUZ2qJPaydB69rk8ArQ5putEe/1cu9HKbYgHjrXggJO3Qf0H08Wwl/Gdl0DqpLyjkwsJla68g0GQHa9Tl6aT/3bzIhmk2K1FOF55fUc5EydMYGGuwrN7qvuA1bZrd1B7n+DiY3dVq2qytUc/y425oyijWQiELzn7/HZ2BWkqfPI9/H4f7tFcHVoY7ArOzdMo+J+QwKKoQBnNfj7J+tPfD3AQlmId3dNzKE/rSSCLJTjng3jkozpcPUC9ko0kvtwSk2I2aGFYVpsLbkxrO7eb/17DIo9jd6DMIRpj9oWbo/WXyTNu/JeDCzeHTLQ5JvzFei3qYSiZGZOO2nITZcMbxYxMY7G4Q1L58E=
conda_forge_output_validation: true
